version: '3'
services:
  prismaserverauthorization:
    image: prismagraphql/prisma:1.17
    restart: always
    hostname: prismaserverauthorization
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases: 
          default:
            connector: postgres
            host: dbserver
            port: 5432
            database: GenetixAuthorization
            # schema: public
            # env_file: './prisma.env'
            user: prisma
            password: prisma
            migrations: true
  dbserver:
    image: postgres
    hostname: dbserver
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      # POSTGRES_DB: GenetixAuthorization
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
  pgadmin:
      image: dpage/pgadmin4
      restart: "unless-stopped"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@4ls.pl
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "5050:80"
      depends_on:
        - dbserver

volumes:
  postgres:
  pgadmin: